version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2017
configuration: Release
install:
  - "C:\\Cygwin64\\setup-x86_64.exe -q -P libmpfr-dev"
  - "C:\\Cygwin64\\setup-x86_64.exe -q -P libgmp-dev"
  - "C:\\Cygwin64\\setup-x86_64.exe -q -P make"
  - PATH c:\\Cygwin64\\bin;c:\\Cygwin64\\usr\\bin;%PATH%
  - "C:\\Cygwin64\\bin\\bash -c '/usr/bin/make --directory=/cygdrive/c/projects/sleef/src/libm-tester -f Makefile.tester'"
  - mkdir build
  - cd build
  - cmake -G"Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=install -DSLEEF_SHOW_CONFIG=1 -DSLEEF_SHOW_ERROR_LOG=1
build_script:
  - cmake --build . --target install --config Release
artifacts:
- path: build\install\**\*
  name: SLEEFWindowsx64
